datatable/humans/urls.py
from django.urls import path

from .views import HumanListViewHtmlTable, HumanListViewHtmlTablePagination, \
                    HumanListViewJqueryTable, HumanListViewJqueryTableAjax, \
                    HumanDetailView


urlpatterns = [
    path('html_table', HumanListViewHtmlTable.as_view(), name='html_table'),
    path('html_table_pagination', HumanListViewHtmlTablePagination.as_view(), name='html_table_pagination'),
    path('jquery_table', HumanListViewJqueryTable.as_view(), name='jquery_table'),
    path('jquery_table_ajax', HumanListViewJqueryTableAjax.as_view(), name='jquery_table_ajax'),
    path('<int:pk>', HumanDetailView.as_view(), name='human_detail' )
]

datatable/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('human/', include('datatable.humans.urls')),

    # API paths
    path('api/human/', include('datatable.humans.api')),
]

datatable/humans/models.py
from django.db import models


class Human(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

datatable/humans/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView

from .models import Human


class HumanListViewHtmlTable(ListView):
    model = Human
    template_name = 'humans/html_table.html'


class HumanListViewHtmlTablePagination(ListView):
    model = Human
    template_name = 'humans/html_table_pagination.html'
    paginate_by = 15


class HumanListViewJqueryTable(ListView):
    model = Human
    template_name = 'humans/jquery_table.html'


class HumanListViewJqueryTableAjax(TemplateView):
    template_name = 'humans/jquery_table_ajax.html'


class HumanDetailView(DetailView):
    model = Human
    pk_url_kwarg = 'pk'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

    <div style="margin-top: 10vh" ></div>

    {% block content %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}

</body>
</html>

templates/humans/html_table.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-12 text-center">
        <table class="table table-hover bg-light text-dark">
            <thead class="thead-dark">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Color</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
                {% for human in object_list %}
                <tr>
                    <td>{{ human.id }}</td>
                    <td>{{ human.name }}</td>
                    <td>{{ human.phone }}</td>
                    <td>{{ human.color }}</td>
                    <td>{{ human.created }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
</div>
{% endblock %}

templates/humans/html_table_pagination.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-12 text-center">
        <table class="table table-hover bg-light text-dark">
            <thead class="thead-dark">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Color</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
                {% for human in object_list %}
                <tr>
                    <td>{{ human.id }}</td>
                    <td>
                        <a href="{% url 'human_detail' human.id %}">{{ human.name }}</a>
                    </td>
                    <td>{{ human.phone }}</td>
                    <td>{{ human.color }}</td>
                    <td>{{ human.created }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

<div class="col-md-2 offset-md-5 text-right">
    {% if is_paginated %}
        <nav aria-label="...">
            <ul class="pagination">
                
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.get_path }}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a class="page-link" disabled>{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item" disabled>
                        <a class="page-link" href="{{ request.get_path }}?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}
</div>

</div>
{% endblock %}

templates/humans/human_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
          <h5 class="card-title">Human Detail</h5>
          <hr>
          <p class="card-text"><b>Name: </b>{{ object.name }}</p>
          <p class="card-text"><b>Phone: </b>{{ object.phone }}</p>
          <p class="card-text"><b>Color: </b>{{ object.color }}</p>
          <p class="card-text"><b>Created At: </b>{{ object.created }}</p>
          <hr>
          <a href="#" class="btn btn-primary">Update</a>
          <a href="#" class="btn btn-danger">Delete</a>
        </div>
      </div>
</div>
{% endblock %}

templates/humans/jquery_table.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-12 text-center">
        <table id="myTable" class="table table-hover bg-light text-dark">
            <thead class="thead-dark">
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Color</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
                {% for human in object_list %}
                <tr>
                    <td>{{ human.id }}</td>
                    <td>{{ human.name }}</td>
                    <td>{{ human.phone }}</td>
                    <td>{{ human.color }}</td>
                    <td>{{ human.created }}</td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

    <div class="col-md-2 offset-md-5 text-right">
        {% if is_paginated %}
            <nav aria-label="...">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{{ request.get_full_path }}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}

                    <li class="page-item active">
                        <a class="page-link" disabled>{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{{ rrequest.get_full_path }}?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
        {% endif %}
    </div>

</div>
{% endblock %}

{% block js %}
<script>
    $(document).ready( function () {
        $('#myTable').DataTable();
    });
</script>
{% endblock %}

templates/humans/jquery_table_ajax.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="col-md-12 text-center">
        <div class="table-responsive-md">
            <table id="myTable" class="table table-hover bg-light text-dark">
                <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Color</th>
                    <th>Created At</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
$(document).ready(function() {
    $('#myTable').DataTable({
        ajax: {
            url: 'http://127.0.0.1:8000/api/human',
            dataSrc: ''
        },
        columns: [
            { data: 'id'},
            { data: 'name'},
            { data: 'phone'},
            { data: 'color'},
            { data: 'created'}
        ]
    });
} );
</script>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tables Comparison</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'html_table' %}">HTML TABLE</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'html_table_pagination' %}">HTML TABLE PAGINATION</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'jquery_table' %}">JQUERY TABLE</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'jquery_table_ajax' %}">JQUERY TABLE AJAX</a>
      </li>
      
    </ul>

    <ul class="navbar-nav ml-auto">
    
      <li class="nav-item">
        <a href="{% url 'api:human_list' %}" class="nav-link">API</a>
      </li>
    
      <!-- <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          API
        </a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">SomethinG</a>
        </div>

      </li> -->

    </ul>
  
  </div>
</nav>